name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          path: dist/storybook
          build_command: PUBLIC_DIR=/retromachina-frontend/ npm run build-storybook